### ISSUE TITLE
can you update this to compile in opencv3?

### ISSUE THREAD

**Issue by atv2016** [liberize/flame-detection-system#1]

**Comment by liberize** [comment]
This repository was created 2 years ago when I was a student. I haven't worked on this since then.
I'm afraid I don't have the energy to maintain it. Pull requests are welcomed though.

**Comment by atv2016** [comment]
Hi Paul,
Thanks for your reply. If you don't mind me asking, did it work well under different lighting conditions/resolutions?

Also, i see a training variable. How would i go about using this, you mentioned providing SVM data? Do i need to train it further, or does it already have complete models.

Why do you say it's not ready for practical application?
Many thanks for your time.
Alef

**Comment by liberize** [comment]
I only tested with several samples, it worked well.
To get SVM data, rebuild project with TRAIN_MODE macro enabled.
**It is just an experimental project.**

**Comment by atv2016** [comment]
Ok, i have converted it to Opencv 3 using the new syntax. It crashed (floating point exception 8) on Mac, in the getMassCenter function, presumingly because of a divide by zero. Setting count to 1 fixed that.

Thanks again.
