### ISSUE TITLE
red moving object

### ISSUE THREAD

**Issue by SabraHashemi** [liberize/flame-detection-system#6]
hi, i know it's for long time ago,
but 
i can detect fire very good by svm, but when i add negative sample about moving red obj, again in the test step , a moving red object detected as fire!! 
did you see this problem before?

**Comment by dtrumpd** [comment]
Hello!
I tried compiling your flame detection package on Visual Studio C++ 2017. It was compiled an linked ok with opencv 2.4.9 - but none of your clips gave a positive result. All clips reported: NO FLAME DETECTED. WHY? A tried all your clips. 2. I tried to launch the program on a Debug step-by-step mode - and it gave errors (in a random way) - the error was while deleting a vector. How to debug the program?
3. what coefficients should be adjusted to increase the probability of recognition?
Thank you in advance.
D Trump (LOL!)

**Comment by liberize** [comment]
@sabrabano0 there are some problems with dynamic features (flicker frequency, area variance...), so i don't feed them to svm. however, these features are critical in distinguishing fire from red moving object.

**Comment by liberize** [comment]
@dtrumpd 
1. i suggest you train the samples first
2. not tested under vs, can't help
3. see TargetExtractor::extract

**Comment by dtrumpd** [comment]
Thank you for your answer,
I have no problem with yr CPP code compilation in Visual Studio C++ = there are no errors at all.
The program (release) works ok, I tried all yr *.avi files, but all of them gave : "No flame detected" , though wile clicking "space" button many times - something is printed on the screen, but always "flame count = 0". I guess, pressing "space" forces the program to analyze in frame-by-frame way - yes? Please, instruct me, how to train the system? What keys on my keyboard should i press to force training? And how much time should i train? And where to see training results and how to implement training to the recognition.
Thank you.

**Comment by liberize** [comment]
you are in train mode, FlameDecider::userInput defined several hotkeys.
i suggest you view whole FlameDecider.cpp, the code is very simple.

**Comment by dtrumpd** [comment]
thank u again. yes - control is simple - i guess, i should press 'o' to start studying after training - ok i pressed 'o' an the program has crashed - i tried several times - and always crash at pressing 'o'.
See the attached screenshot. So, please, point me - how to eliminate the crash at pressing 'o' key. Thanx a lot.
![opencv error bad argument](https://user-images.githubusercontent.com/32157742/30741885-0221f42c-9f97-11e7-9b3c-2f1b71d2f6fc.jpg)

**Comment by dtrumpd** [comment]
so..what???? why are you silent???

**Comment by dtrumpd** [comment]
see here:
// check parameter types and sizes
    if( !CV_IS_MAT(train_data) || CV_MAT_TYPE(train_data->type) != CV_32FC1 )
        CV_ERROR( CV_StsBadArg, "train data must be floating-point matrix" );
==******==
CV_32FC1 seems to be ok in yr program, so, the error is due to !CV_IS_MAT(train_data) - yes?
there something wrong with train_data  (i guess) - where to see the train_data in yr prg ? advise pls.
thanks again and a lot...

**Comment by liberize** [comment]
the error msg is obvious, i believe it's not hard to fix. as i said in
readme, i won't respond to this kind of problem. sorry.

2017年9月22日 19:08，"dtrumpd" <notifications@github.com>写道：

**Comment by dtrumpd** [comment]
It's a pity that u a silent...
well, i guess that the error was due to the content of the file sample.txt (it has zero length=0) (btw - why? how to force yr program to generate a new sample.txt file?)?
ok. (that's bad) - I took the sample6.txt from yr package and renamed it to sample.txt ( i use 6.avi).
And after that the opencv error ("train data must be floating-point matrix") disappeared. well. but.. nevertheless, again, with this new sample.txt (17 kb of floating-point data) i gave "No flame detected" - why?  i have training data now!... I stuck here... pls advice what to do then... thanx a lot.....

**Comment by dtrumpd** [comment]
please respond - do't go away!!!!
I fixed that problem - but yr prg does not generate the sample.txt file
is it mine error? - no - it is yr error (sorry)
I wrote - i took the sample6.txt from yr package and nevertheless i got "No flame detected" with the train data (sample.txt = 17 kb) - how you explain it?????

**Comment by liberize** [comment]
sample6 works best on clip6, etc

2017年9月22日 19:45，"dtrumpd" <notifications@github.com>写道：

**Comment by liberize** [comment]
this project is only intended for algorithm studying, i have no time
dealing with those who don't even look into the code.
i'll mute the thread.

2017年9月22日 19:48，"dtrumpd" <notifications@github.com>写道：

**Comment by dtrumpd** [comment]
it is bad that u don't want to explain your own code...
It is yr program - so explain it.
yr prg does not generate neither svmdata.xml file nor sample.txt file
and it is not mine flaw.... it is yr flaw....

**Comment by dtrumpd** [comment]
Explain me where i can get svmdata.xml for 6.avi ???????
